In [15]:
import pandas as pd
import config as cfg

# Passengers Dataset

## 1) Importing data and skimming through

In [16]:
df_passengers = pd.read_csv(cfg.PASSENGERS_DATA)
df_passengers.head()

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,GIORNO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,...,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio,Tipo Documento,FASCIA ETA,3nazionalita,compagnia%aerea,num volo
0,ALB,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,...,Fly Dubai,FZ1681,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,NaN,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,...,ITA Airways,AZ0609,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,ALB,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,...,Ryanair DAC,FR8400,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,AFG,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,...,Turkish Airlines,TK1865,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,ALB,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,...,Fly Dubai,FZ1571,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571

In [17]:
display(df_passengers.columns, df_passengers.shape)
df_passengers.isnull().sum().sort_values(ascending=False)

Index(['NAZIONALITA', 'AREOPORTO_ARRIVO', 'AREOPORTO_PARTENZA',
       'ANNO_PARTENZA', 'MESE_PARTENZA', 'GIORNO_PARTENZA', 'DATA_PARTENZA',
       'DESCR_AEREOPORTO_ARR', 'DESCR_AEREOPORTO_PART', 'CITTA_ARR',
       'CITTA_PARTENZA', 'CODICE_PAESE_ARR', 'CODICE_PAESE_PART', 'PAESE_ARR',
       'PAESE_PART', 'ZONA', 'ENTRATI', 'INVESTIGATI', 'ALLARMATI',
       'TIPO_DOCUMENTO', 'GENERE', 'FASCIA_ETA', 'FLAG_TRANSITO',
       'COMPAGNIA_AEREA', 'NUMERO_VOLO', 'ESITO_CONTROLLO', 'note_operatore',
       'codice_rischio', 'Tipo Documento', 'FASCIA ETA', '3nazionalita',
       'compagnia%aerea', 'num volo'],
      dtype='object')

(5095, 33)

codice_rischio           5054
note_operatore           5034
ESITO_CONTROLLO          1289
NAZIONALITA               116
COMPAGNIA_AEREA            87
NUMERO_VOLO                70
TIPO_DOCUMENTO             62
GENERE                     45
INVESTIGATI                 0
compagnia%aerea             0
3nazionalita                0
FASCIA ETA                  0
Tipo Documento              0
FLAG_TRANSITO               0
FASCIA_ETA                  0
ALLARMATI                   0
ENTRATI                     0
AREOPORTO_ARRIVO            0
ZONA                        0
PAESE_PART                  0
PAESE_ARR                   0
CODICE_PAESE_PART           0
CODICE_PAESE_ARR            0
CITTA_PARTENZA              0
CITTA_ARR                   0
DESCR_AEREOPORTO_PART       0
DESCR_AEREOPORTO_ARR        0
DATA_PARTENZA               0
GIORNO_PARTENZA             0
MESE_PARTENZA               0
ANNO_PARTENZA               0
AREOPORTO_PARTENZA          0
num volo                    0
dtype: int64

There are five duplicate columns that must be removed since they include inconsistent data. <br>
Then we can proceed with translating our columns.

In [18]:
duplicates = ['FASCIA_ETA', 'TIPO_DOCUMENTO', 'NAZIONALITA', 'NUMERO_VOLO', 'COMPAGNIA_AEREA']
df_passengers.drop(columns=duplicates, errors='ignore', inplace=True)

In [19]:
df_passengers.rename(columns=cfg.COLUMN_MAPPING_PASSENGERS, inplace=True)
display(df_passengers.columns)
display(df_passengers.isnull().sum().sort_values(ascending=False))

Index(['arrival_airport_code', 'departure_airport_code', 'departure_year',
       'departure_month', 'departure_day', 'departure_date',
       'arrival_airport_name', 'departure_airport_name', 'arrival_city',
       'departure_city', 'arrival_country_code', 'departure_country_code',
       'arrival_country', 'departure_country', 'zone', 'entries_count',
       'investigated_count', 'flagged_count', 'gender', 'transit_flag',
       'control_result', 'operator_notes', 'risk_code', 'document_type',
       'age_range', 'nationality', 'airline', 'flight_number'],
      dtype='object')

risk_code                 5054
operator_notes            5034
control_result            1289
gender                      45
arrival_airport_code         0
departure_airport_code       0
airline                      0
nationality                  0
age_range                    0
document_type                0
transit_flag                 0
flagged_count                0
investigated_count           0
entries_count                0
zone                         0
departure_country            0
arrival_country              0
departure_country_code       0
arrival_country_code         0
departure_city               0
arrival_city                 0
departure_airport_name       0
arrival_airport_name         0
departure_date               0
departure_day                0
departure_month              0
departure_year               0
flight_number                0
dtype: int64

In [32]:
df_passengers.head()

,arrival_airport_code,departure_airport_code,departure_year,departure_month,departure_day,departure_date,arrival_airport_name,departure_airport_name,arrival_city,departure_city,...,gender,transit_flag,control_result,operator_notes,risk_code,document_type,age_range,nationality,airline,flight_number
0,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,Durban,...,F,Singola Tratta,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,New York,...,F,Singola Tratta,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,Tirana,...,f,Singola Tratta,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,Istanbul,...,M,Singola Tratta,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,Male,...,F,Singola Tratta,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571

# Cases Dataset

In [20]:
df_cases = pd.read_csv(cfg.CASES_DATA)
display(df_cases.head())
df_cases.shape

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,CITTA_PARTENZA,...,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,CODICE PAESE ARR,3zona,paese%arr,tot voli
0,Voli con Allarmi,FCO,IST,2024,01,2024-01-30 09:15:00,Fiumicino,Havalimani,Roma,Istanbul,...,5,1,Manuale,NaN,NaN,Turchia,ITA,5,Italia,1
1,Viaggiatori con Allarmi,CIA,STN,2024,02,2024-02-03 13:15:00,Ciampino,Stansted,Roma,Londra,...,5,5,Manuale,NaN,NaN,Regno Unito,ITA,5,Italia,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024,01,2024-01-15 08:45:00,Fiumicino,London Heathrow,Roma,Londra,...,5,110,TSC,NaN,NaN,Regno Unito,ITA,5,Italia,110
3,Voli con Allarmi,MXP,LHR,2024,02,2024-02-02 08:40:00,Malpensa,London Heathrow,Milano,Londra,...,2,1,SDI,NaN,NaN,Regno Unito,ITA,2,Italia,1
4,Viaggiatori con Allarmi,PSA,BRS,2024,02,2024-02-16 12:50:00,Galileo Galilei,Bristol,Pisa,Bristol,...,8,2,INTERPOL,NaN,NaN,Regno Unito,ITA,8,Italia,2

(5080, 24)

In [21]:
duplicates = ['PAESE_ARR', 'paese%arr', 'CODICE_PAESE_PART', 'PAESE_PART', 
            'DESCR_AEREOPORTO_PART', 'CITTA_PARTENZA', 'ZONA', '3zona', 
            'ANNO_PARTENZA', 'MESE_PARTENZA', 'TOT', 'CODICE PAESE ARR']

df_cases.drop(columns=duplicates, errors='ignore', inplace=True)
df_cases.columns

Index(['OCCORRENZE', 'AREOPORTO_ARRIVO', 'AREOPORTO_PARTENZA', 'DATA_PARTENZA',
       'DESCR_AEREOPORTO_ARR', 'CITTA_ARR', 'CODICE_PAESE_ARR',
       'MOTIVO_ALLARME', 'note_operatore', 'flag_rischio', 'Paese Partenza',
       'tot voli'],
      dtype='object')

In [22]:
df_cases['tot voli'] = df_cases['tot voli'].astype(str).str.extract(r'(\d+)').astype(float).fillna(0).astype(int)

In [23]:
df_cases['AREOPORTO_ARRIVO'] = df_cases['AREOPORTO_ARRIVO'].str.upper()
df_cases['AREOPORTO_PARTENZA'] = df_cases['AREOPORTO_PARTENZA'].str.upper()

In [24]:
df_cases['CODICE_PAESE_ARR'] = df_cases['CODICE_PAESE_ARR'].replace('IT', 'ITA')

In [25]:
df_cases['CODICE_PAESE_ARR'].replace('GB', 'GBR', inplace=True)

C:\Users\AFGWO\AppData\Local\Temp\ipykernel_9960\2356592979.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cases['CODICE_PAESE_ARR'].replace('GB', 'GBR', inplace=True)

In [26]:
df_cases['CODICE_PAESE_ARR'].unique()

array(['ITA', 'DEU', 'FRA', 'TUR', 'GBR', 'ESP'], dtype=object)

In [27]:
df_cases.head()

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,CITTA_ARR,CODICE_PAESE_ARR,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,tot voli
0,Voli con Allarmi,FCO,IST,2024-01-30 09:15:00,Fiumicino,Roma,ITA,Manuale,NaN,NaN,Turchia,1
1,Viaggiatori con Allarmi,CIA,STN,2024-02-03 13:15:00,Ciampino,Roma,ITA,Manuale,NaN,NaN,Regno Unito,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024-01-15 08:45:00,Fiumicino,Roma,ITA,TSC,NaN,NaN,Regno Unito,110
3,Voli con Allarmi,MXP,LHR,2024-02-02 08:40:00,Malpensa,Milano,ITA,SDI,NaN,NaN,Regno Unito,1
4,Viaggiatori con Allarmi,PSA,BRS,2024-02-16 12:50:00,Galileo Galilei,Pisa,ITA,INTERPOL,NaN,NaN,Regno Unito,2

In [28]:
df_cases['Paese Partenza'] = df_cases['Paese Partenza'].map(cfg.COUNTRY_MAPPING).fillna("UNK")
df_cases['Paese Partenza'].unique()

array(['TUR', 'GBR', 'MKD', 'QAT', 'MDA', 'EGY', 'SAU', 'SGP', 'TUN',
       'ALB', 'HKG', 'MAR', 'TWN', 'SRB', 'OMN', 'DZA', 'ISR', 'ARE',
       'KOR', 'IRN', 'MDV', 'BRA', 'CHN', 'JOR', 'USA', 'ETH', 'ARG',
       'DOM', 'IND', 'AZE', 'CPV', 'TZA', 'SEN', 'KWT', 'MEX', 'CAN',
       'BHR', 'ARM', 'MUS', 'KEN', 'MNE', 'LBY', 'XKX', 'LBN', 'GEO',
       'JPN', 'UZB', 'KAZ', 'ATG', 'JAM'], dtype=object)

In [29]:
display(df_cases.columns)
df_cases.rename(columns=cfg.COLUMN_MAPPING_CASES, inplace=True)
df_cases.columns

Index(['OCCORRENZE', 'AREOPORTO_ARRIVO', 'AREOPORTO_PARTENZA', 'DATA_PARTENZA',
       'DESCR_AEREOPORTO_ARR', 'CITTA_ARR', 'CODICE_PAESE_ARR',
       'MOTIVO_ALLARME', 'note_operatore', 'flag_rischio', 'Paese Partenza',
       'tot voli'],
      dtype='object')

Index(['event_type', 'arrival_airport', 'departure_airport', 'departure_date',
       'arrival_airport_name', 'arrival_city', 'arrival_country_code',
       'alarm_reason', 'operator_notes', 'risk_flag', 'departure_country_name',
       'total_flights'],
      dtype='object')